# Set the format of the chat.
# Formatters ; 
# {WORLDNAME} : The name of the world the player is in.
# {DISPNAME} : The display name of the player who sent the message.
# {NAME} : The real, untouched username of the player who sent the message.
# {MESSAGE} : The message.
# {PREFIX} : The group prefix of the player.
# {SUFFIX} : The group suffix of the player.
# {CHANNELNAME} : The name of the channel.
# {CHANNELNICK} : The nickname of the channel.
# {CHANNELCOLOR} : The color of the channel.
# {COLOR.COLORCODE} : The color code, get a list at jd.bukkit.org/apidocs/org/bukkit/ChatColor.html#enum_constant_detail.
formats:
    default: "<{WORLDNAME}> {CHANNELCOLOR}[{CHANNELNICK}]{COLOR.WHITE} [{PREFIX}] <{DISPNAME}> : {MESSAGE}"
